# Hypridle configuration

general {
    lock_cmd = pidof hyprlock || hyprlock       # Command to run when locking
    before_sleep_cmd = loginctl lock-session    # Command before sleep
    after_sleep_cmd = hyprctl dispatch dpms on  # Turn screen back on after sleep
}

listener {
    timeout = 300                                # 5 minutes
    on-timeout = hyprctl dispatch dpms off       # Turn off screen
    on-resume = hyprctl dispatch dpms on         # Turn screen back on
}

listener {
    timeout = 600                                # 10 minutes
    on-timeout = loginctl lock-session           # Lock screen
}
